config/routes.rb
Rails.application.routes.draw do
  get 'answers/', to: 'questions#index'

  get 'answers/show'

  get 'answers/new'

  get 'answers/create'

  get 'answers/edit'

  get 'answers/update'

  get 'answers/destroy'

  devise_for :users
  root 'questions#index'
  resources :questions

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/question.rb
class Question < ApplicationRecord
 	has_many :answers
 	belongs_to :user

	validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :send_email
	  def send_email
	  	UserMailer.welcome_email(self).deliver_now
	  end  	
  end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @answers = Answer.all
  end

  def show
    @question = Answer.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.create(questions_params)
    @question.user = current_user
    if @question.save
      redirect_to question_path(@question), notice: "Pregunta publicada exitosamente"
    else
      render :edit      
    end
  end
  
  def edit
   @question = Question.find(params[:id])
  end

  def update
      @question = Question.find(params[:id])
    if @question.update(questions_params)
      redirect_to question_path(@question), notice: "Tu pregunta ha sido actualizada"
    else
      render :edit, notice: "No se pudo actualizar el registro, intente de nuevo"
    end
  end

def destroy
  question = Question.find(params[:id])
  question.destroy

  redirect_to questions_path, notice: "Tu pregunta ha sido borrada"
end

private
def questions_params
  params.require(:question).permit(:title, :description, :vote, :id)
end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_helper.rb
module QuestionHelper
	def form_title
		@question.new_record? ? "Publicar Pregunta" : "Modificar Pregunta"
	end

	def form_submit
		@question.new_record? ? "Preguntar!" : "Re-Preguntar!"
	end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Overflow</title>

  <!--CDN Ionic Framework-->
  <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
 <nav class="navbar navbar-expand-lg navbar-dark fixed bg-dark">
  <img class="img-fluid img-thumbnail rounded-circle" src="/icon.png" alt="logo" style="width: 50px; ">
  <%= link_to "OverFlow", "/", class: 'h3 nav-link active text-white' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Más Vistas</a>
      </li>
      <li class="nav-item">
        <% if signed_in? %>
        <%= link_to("Salir", "/users/sign_out", :method => :delete, class: "nav-link active text-right") %>
        
      </li>
      <% else %>
      <li>
       <%= link_to("Ingresar", "/users/sign_in", class: "nav-link active text-right") %>
     </li>
     <li>
       <%= link_to("Registrarse", "/users/sign_up", class: "nav-link active text-right") %>
     </li>         
     <% end %>
   </ul> 
   <% if signed_in? %>
   <small class="text-white"> <%= current_user.email %> &nbsp &nbsp </small>
   <% end %>     
   <form class="form-inline">        
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Search</button>
  </form>
</div>
</nav>

<!--FLASH NOTICE-->
<% if flash[:notice] %>
<div class="alert alert-info text-center"><%= flash[:notice] %></div>
<% end %>

<div class="container"> 
  <div class="justify-content-md-center">
    <br>
    <%= yield %>
  </div>
</div>
<section class="bg-dark" style="height: 200px">  <!--pendiente-->
  <br>
  <footer> 
    <h4 class="text-center text-white">Todos los derechos reservados</h4>
  </footer>
</section>  
</body>

</html>

app/views/questions/_new.html.erb
<div class="row">
  <div class="col-md-8 mx-auto">
    <% if signed_in? %> 
    <div class="container">
      <div>
        <hr>
        <h1><%= form_title %></h1>
        <%= form_for @question do |f| %>
        <div class="form-group">
          <%= f.text_field :title, class: "form-control input-lg", placeholder: "Titulo" %>
        </div>
        <div class="form-group">
          <%= f.text_area :description, class: "form-control input-lg", placeholder: "Descripción", rows: 7, cols: 4 %>
        </div>
        <div>
          <%= f.submit form_submit, class: "btn btn-primary btn-lg btn-block" %>
        </div>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/questions/_show.html.erb
 <br>
 <hr>
 <h5 class="card card-footer bg-info text-white text-center">Pregunta <%= @question.id %></h5>
 <div class="text-right"> 
 	<%= link_to "Editar", edit_question_url, class: 'btn btn-outline-info' %>
 </div><br>

 <div class="table-responsive">
 	<table class="table">
 		<tbody>
 			<tr>
 				<td> 
 					<div class="text-muted  text-center h6"> 
 						<i class="ion-arrow-up-b"></i><br>
 						<%= @question.vote %> <br><i class="ion-arrow-down-b"></i><br>
 						<small class="h-50 text-success text-center">Vote</small>
 					</div>  
 				</td>
 				<td>
 					<h3><%= @question.title %></h3>      	
 					<div>
 						<p class="h6"><%= @question.description %><small style="color: #FF7F50; font-style: bold">Publicado por:</small></p></div>

 					</td>
 				</tr>         
 			</tbody>      
 		</table>
 	</div>

app/views/questions/edit.html.erb
<%= render 'new' %>

app/views/questions/index.html.erb
 <div class="card card-default">
  <div>
    <div class="card-header">
    <p class="card-title">Stack Overflow en español es un sitio de preguntas y respuestas para programadores y profesionales de la informática. Únete a ellos; toma menos de un minuto:</p>
      
    <%= link_to 'Sign Up', '/users/sign_up', class: "btn btn-outline-success" %>
  </div>

    <div class="card-body">

      <b>Así es como funciona:</b>
      <ol>
        <li>
          Cualquiera puede formular una pregunta
        </li>
        <li>
          Cualquiera puede responder
        </li>
        <li>
          Se vota a favor de las mejores respuestas, y éstas suben a los primeros puestos
        </li>
      </ol>
    </div>
   
  </div>
</div>

 
<br>  
<div class="panel panel-default"> 
 <h3 class="text-dark">PREGUNTAS</h3>
</div> 
<div class="text-right">
  <%= link_to("Preguntar", "/questions/new" , class: "btn btn-outline-success") %>    
</div>
<br>

<table class="table table-sm">
  <% @questions.each do |question| %>

  <tbody>
    <tr>  
    <td> 
      <div class="text-muted  text-center h6"> 
        <%= question.vote %> <br>
        <small class="h-50 text-success text-center">Vote</small>
      </div>  
    </td>
    <td> 
      <small class="text-center"> Respuestas </small>
    </td>
    <td> 
      <%= link_to question.title, question_path(question), title: question.description %><br> 
      <small class="h-75" style="color: #E82C0C; font-style: bold">Publicado por:
       <% if signed_in? %>
       <%= current_user.email %>
       <% end %>
     </small>
   </td>
    <% if signed_in? %> 
   <td>
    <%= link_to "Eliminar",  question_path(question), method: :delete, data: {confirm: "¿Estas seguro?"}, class: 'btn btn-outline-danger text-right' %></td> 
    <% end %>
    <% end %>
   </tr> 

  
  </tbody>
  
</table>
<div class="panel panel-default">
    <h1>Hola</h1>
</div>

app/views/questions/new.html.erb
<%= render 'new' %>

app/views/questions/show.html.erb
<%= render 'show' %>